sudo: false
cache: bundler
language: ruby
rvm:
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
before_install: gem install bundler -v 2.1.4
notifications:
  email:
    on_success: never # default: change
    on_failure: never # default: always
