sudo: false
cache: bundler
language: ruby
rvm:
  - 2.6
  - 2.7
  - 3.0
before_install: gem install bundler -v 2.2.17
notifications:
  email:
    on_success: never # default: change
    on_failure: never # default: always
