sudo: false
cache: bundler
language: ruby
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1
before_install: gem install bundler -v 2.1.4
notifications:
  email:
    on_success: never # default: change
    on_failure: never # default: always
