# This cop checks that the ABC size of methods is not higher than the configured maximum. The current default is a little
# low and produces many false positives.
Metrics/AbcSize:
  Max: 40 # The default is 15.

# Metrics/BlockLength checks the lines in a block. The default is 25.
Metrics/BlockLength:
  Exclude:
    - spec/**/* # The RSpec DSL uses large blocks.
    - db/migrate/**/* # The Rails migrate folder has large blocks.
    - config/routes.rb # The Rails routes file is one large block.

# Metrics/ClassLength checks the number of lines in a class.
Metrics/ClassLength:
  Max: 200 # 100 is the default which is too restrictive.

# Metrics/MethodLength checks the number of lines in a method.
Metrics/MethodLength:
  Max: 15
  Exclude:  # skip all of the following....
    - db/migrate/**/*

# Metrics/ModuleLength checks the number of lines in a module.
Metrics/ModuleLength:
  Max: 200 # 100 is the default which is too restrictive.

# Metrics/ParameterLists validates the number of parameters that a method can take.
Metrics/ParameterLists:
  Max: 7 # The default limit is 5 which is a bit restrictive.
