Naming/BlockForwarding:
  EnforcedStyle: explicit # See https://github.com/roberts1000/rubocop_plus/issues/358

# This cop checks for the use of 'is_', 'has_' and 'have_' in front of methods. Keep prefixes can sometimes improve readability.
# For example, 'is_cat?'' has a different meaning than 'has_cat?' And just 'cat?' is ambiguous.
Naming/PredicatePrefix:
  Enabled: false
