Rails/ActionOrder:
  Enabled: false # See https://github.com/roberts1000/rubocop_plus/issues/233

# Rails/FilePath ensures Rails.root.join('path', 'to') is used instead of "#{Rails.root}/path/to". This cop isn't necessary
# since Ruby will automatically convert file path separators.
Rails/FilePath:
  Enabled: false

Performance/RedundantMerge:
  Enabled: false

Rails/RootPathnameMethods:
  Exclude:
    - spec/rails_helper.rb # See https://github.com/roberts1000/rubocop_plus/issues/348
