# Checks for multiple expectations in a test. Prefer allowing any number of expecations.
# https://github.com/rubocop-hq/rubocop-rspec/blob/v1.37.1/lib/rubocop/cop/rspec/multiple_expectations.rb#L48
RSpec/MultipleExpectations:
  Enabled: false
