# Checks for multiple expectations in a test. Prefer allowing any number of expecations.
# https://github.com/rubocop-hq/rubocop-rspec/blob/v1.37.1/lib/rubocop/cop/rspec/multiple_expectations.rb#L48
RSpec/MultipleExpectations:
  Enabled: false

# Checks the number of lines in the spec example. The default is 5, which frequently can be a bit tight.
# https://github.com/rubocop-hq/rubocop-rspec/blob/v1.37.1/lib/rubocop/cop/rspec/example_length.rb#L28
RSpec/ExampleLength:
  Max: 8
